configurations:
  # SourceryAppGenerator
  - sources:
      - ../../SourceryAppGenerator/
    templates:
      - Templates
    output:
      "../SourceryAppGeneratorTests/Mocks/Generated"
    args:
      autoMockableTestableImports: []
      autoMockableImports: [""]